config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end

  resources :orders, only: [ :index, :show, :create ]

  root 'products#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :find_categories

  def initialize_cart
    @cart = Cart.build_from_hash session
  end

  def find_categories
    @categories = Category.all
  end

  def authenticate_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You are not allowed to perform that operation."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cart.html.haml
-if @cart
  %p.navbar-text.navbar-right
    -if @cart.empty?
      Your cart is empty.
    -else
      =link_to "You have #{pluralize @cart.count, "item"} items.", cart_path

app/views/application/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Tuts+ Office Supplies", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Products", products_path %></li>
        <li class="dropdown">
          <%= link_to "#", data: { toggle: "dropdown" } do %>
              Categories
              <span class="caret"></span>
          <%- end %>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
                <li><%= link_to category.name, category %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
            Logged in as <%= current_user.name %>.
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "Login", new_user_session_path, class: "navbar-link" %>
        <% end %>
      </p>
      <%= render "cart" %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>